language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

before_script:
  - go get github.com/google/go-querystring/query
  - go get github.com/Sirupsen/logrus
  - go get github.com/stretchr/testify/assert

script: go test ./... -v
